# Load Data

In [1]:
import hickle  as hkl

In [2]:
data2 =hkl.load('./Gen_data/CROSS_Net_input.hkl')

# Generate LSTM NetWork

In [3]:
import theano

Using gpu device 0: GeForce GTX TITAN X (CNMeM is disabled, cuDNN 5105)


In [11]:
import numpy as np

In [4]:
from lasagne.layersgne.layers import InputLayer
from lasagne.layers import LSTMLayer
from lasagne.layers import ReshapeLlasagne
from lasagne.layers import DenseLayer

In [13]:
from lasagne.updates import adam
from lasagne.objectives import squared_error

from nolearn.lasagne import NeuralNet
from nolearn.lasagne import TrainSplit

In [75]:
cutdown_len,num_units, num_classes = 13, 10, 5
layer1 = InputLayer(shape=(None,1,cutdown_len))  #输入是序列的原始编码
layer2 = LSTMLayer(layer1,num_units= num_units)
layer3 = ReshapeLayer(layer2,(-1,num_units))
layer4 = DenseLayer(layer3,num_units=5 ,nonlinearity=tanh)
network = DenseLayer(layer4,num_units=1,nonlinearity=tanh)

In [76]:

lr = theano.shared(np.float32(1e-4))

net = NeuralNet(
            network,
            max_epochs=50,
            update=adam,
            update_learning_rate=lr,
            train_split=TrainSplit(eval_size=0.1),
                regression = True,
            objective_loss_function = squared_error,
            #on_epoch_finished=[
            #    AdjustVariable(lr, target=1e-8, half_life=20)],
            verbose=4)

In [77]:
net.fit(X_train, y_train)

# Neural Network with 1051 learnable parameters

## Layer information

  #    name  size
---  ------  ------
  0          1x13
  1          1x10
  2          10
  3          5
  4          1



TypeError: Bad input argument to theano function with name "/home/yinqijin/.local/lib/python2.7/site-packages/nolearn/lasagne/base.py:639" at index 0 (0-based).  
Backtrace when that variable is created:

  File "/home/yinqijin/anaconda2/lib/python2.7/site-packages/ipykernel/kernelbase.py", line 390, in execute_request
    user_expressions, allow_stdin)
  File "/home/yinqijin/anaconda2/lib/python2.7/site-packages/ipykernel/ipkernel.py", line 196, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/home/yinqijin/anaconda2/lib/python2.7/site-packages/ipykernel/zmqshell.py", line 501, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/home/yinqijin/anaconda2/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2717, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "/home/yinqijin/anaconda2/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2821, in run_ast_nodes
    if self.run_code(code, result):
  File "/home/yinqijin/anaconda2/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2881, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-75-364997f354b2>", line 2, in <module>
    layer1 = InputLayer(shape=(None,1,cutdown_len))  #输入是序列的原始编码
  File "/home/yinqijin/anaconda2/bin/src/lasagne/lasagne/layers/input.py", line 63, in __init__
    input_var = input_var_type(var_name)
Wrong number of dimensions: expected 3, got 2 with shape (128, 13).

# Import Data

In [15]:
import numpy as np
import pandas as pd


In [28]:
temp =[]
for string in data2['seq']:
    temp.append([ item for item in string])
    

In [30]:

#j将碱基序列转化为数字序列
d = {'a':1, 'A':1, 'g':2, 'G':2, 'c':3, 'C':3, 't':4, 'T':4, 'N':5, 'n':5}
func = lambda x:d[x]

X_pd = pd.DataFrame(temp)


In [39]:
X_=X_pd.applymap(func)

In [40]:
X=X_.values[:,:]
type(X)

In [42]:
Y = data2['score']

In [43]:
Y_ = [ item[(len(item)-1)/2] for item in Y]
Y_ = np.array(Y_)



In [44]:
print X[:2]
print Y_[:2]

[[2 2 2 1 2 3 3 3 1 2 1 1 2]
 [2 2 1 2 3 3 3 1 2 1 1 2 2]]
[ 0.015  0.002]


In [45]:
from sklearn.cross_validation import ShuffleSplit
rs = ShuffleSplit(len(Y_), n_iter=1)

In [47]:
for train_idx, test_idx in rs:
    X_train = X[train_idx,:]
    y_train = Y_[train_idx]
    X_test = X[test_idx,:]
    y_test = Y_[test_idx]

In [48]:
X_train = X_train.astype('float32')
y_train = y_train.astype('float32')
X_test = X_test.astype('float32')
y_test = y_test.astype('float32')

In [78]:
print X_train[:2]
print y_train[:2]

[[ 1.  2.  3.  1.  3.  3.  3.  1.  3.  3.  4.  2.  3.]
 [ 1.  1.  4.  1.  4.  4.  4.  1.  1.  3.  2.  4.  3.]]
[-1.05499995  0.        ]


# Test Network

In [53]:
net.fit(X_train, y_train)

ValueError: new_order[2] is 2, but the input only has 2 axes.

In [ ]:
wo 